import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import {} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './incoming-emails.reducer';

export const IncomingEmailsDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const incomingEmailsEntity = useAppSelector(state => state.incomingEmails.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="incomingEmailsDetailsHeading">IncomingEmails</h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">ID</span>
          </dt>
          <dd>{incomingEmailsEntity.id}</dd>
          <dt>
            <span id="userId">User Id</span>
          </dt>
          <dd>{incomingEmailsEntity.userId}</dd>
          <dt>
            <span id="topicId">Topic Id</span>
          </dt>
          <dd>{incomingEmailsEntity.topicId}</dd>
          <dt>
            <span id="postId">Post Id</span>
          </dt>
          <dd>{incomingEmailsEntity.postId}</dd>
          <dt>
            <span id="raw">Raw</span>
          </dt>
          <dd>{incomingEmailsEntity.raw}</dd>
          <dt>
            <span id="error">Error</span>
          </dt>
          <dd>{incomingEmailsEntity.error}</dd>
          <dt>
            <span id="messageId">Message Id</span>
          </dt>
          <dd>{incomingEmailsEntity.messageId}</dd>
          <dt>
            <span id="fromAddress">From Address</span>
          </dt>
          <dd>{incomingEmailsEntity.fromAddress}</dd>
          <dt>
            <span id="toAddresses">To Addresses</span>
          </dt>
          <dd>{incomingEmailsEntity.toAddresses}</dd>
          <dt>
            <span id="ccAddresses">Cc Addresses</span>
          </dt>
          <dd>{incomingEmailsEntity.ccAddresses}</dd>
          <dt>
            <span id="subject">Subject</span>
          </dt>
          <dd>{incomingEmailsEntity.subject}</dd>
          <dt>
            <span id="rejectionMessage">Rejection Message</span>
          </dt>
          <dd>{incomingEmailsEntity.rejectionMessage}</dd>
          <dt>
            <span id="isAutoGenerated">Is Auto Generated</span>
          </dt>
          <dd>{incomingEmailsEntity.isAutoGenerated ? 'true' : 'false'}</dd>
          <dt>
            <span id="isBounce">Is Bounce</span>
          </dt>
          <dd>{incomingEmailsEntity.isBounce ? 'true' : 'false'}</dd>
          <dt>
            <span id="imapUidValidity">Imap Uid Validity</span>
          </dt>
          <dd>{incomingEmailsEntity.imapUidValidity}</dd>
          <dt>
            <span id="imapUid">Imap Uid</span>
          </dt>
          <dd>{incomingEmailsEntity.imapUid}</dd>
          <dt>
            <span id="imapSync">Imap Sync</span>
          </dt>
          <dd>{incomingEmailsEntity.imapSync ? 'true' : 'false'}</dd>
          <dt>
            <span id="imapGroupId">Imap Group Id</span>
          </dt>
          <dd>{incomingEmailsEntity.imapGroupId}</dd>
          <dt>
            <span id="imapMissing">Imap Missing</span>
          </dt>
          <dd>{incomingEmailsEntity.imapMissing ? 'true' : 'false'}</dd>
          <dt>
            <span id="createdVia">Created Via</span>
          </dt>
          <dd>{incomingEmailsEntity.createdVia}</dd>
        </dl>
        <Button tag={Link} to="/incoming-emails" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/incoming-emails/${incomingEmailsEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

export default IncomingEmailsDetail;
